### PR TITLE
added missing cd cmd to change directory to hooks

### PR DESCRIPTION
**Pull request by nagakputtagunta**

### CODE REVIEW

**Comment by msolomonTMG** [comment]
Hey @nagakputtagunta  -- did copying and pasting ``git rev-parse --git-dir`/hooks`` (including the backticks) change directory for you? It worked for me without having to use cd (gif attached). Let me know and if it doesn't work, I'd be happy to merge!

image of changing directory

**Comment by nagakputtagunta** [comment]
Hi @msolomonTMG, it doesn't work for me without adding `cd` to the front of it. If it makes any difference, I am in `bash`.

Screen recording

**Comment by msolomonTMG** [comment]
Hey @nagakputtagunta - I am curious to know if this [line](https://github.com/nagakputtagunta/timesheet-githook/blob/nagakputtagunta-patch-1/post-commit#L31) should get a similar change. Does the hook have trouble reading your credentials when you run it? Thanks!

**Comment by nagakputtagunta** [comment]
I think that might be fine since you are using that to build the path to the file and not actually changing to that folder via the shell. Will confirm in a bit.

**Pull request merged**
